### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by arenas7307979** [petercorke/spatialmath-python#52]
from spatialmath import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/datasets/magnetic_tool/spatialmath-python/spatialmath/__init__.py", line 1, in <module>
    from spatialmath.pose2d import SO2, SE2
  File "/datasets/magnetic_tool/spatialmath-python/spatialmath/pose2d.py", line 26, in <module>
    from spatialmath.base import argcheck
  File "/datasets/magnetic_tool/spatialmath-python/spatialmath/base/__init__.py", line 8, in <module>
    from spatialmath.base.transforms3d import *  # lgtm [py/polluting-import]
  File "/datasets/magnetic_tool/spatialmath-python/spatialmath/base/transforms3d.py", line 24, in <module>
    import spatialmath.base.symbolic as sym
AttributeError: module 'spatialmath' has no attribute 'base'

**Comment by Zyszu200** [comment]
I am also having this problem. It looks like spatialmath is missing somehow base attribute.

**Comment by Zyszu200** [comment]
Updating python and pip to latest version solved problem for me 😆.

**Comment by StephLin** [comment]
It seems that the following statement does not work in **Python 3.6** (but works in 3.7, which is mentioned in https://github.com/python/cpython/issues/74210):

https://github.com/petercorke/spatialmath-python/blob/da5aa910617869715da9e661da475ba83b28c59f/spatialmath/base/transforms3d.py#L24

The issue can be fixed by replacing it with

```python
from spatialmath.base import symbolic as sym
```

I am working on submitting a PR for it as this awesome package claims to support Python 3.6 as well.

**Comment by jhavl** [comment]
Thanks everyone, this issue should be fixed with the latest pull request.

**Comment by me-mechmind** [comment]
I encountered a similar problem in the files `pose2d.py` and `baseposematrix.py`.
Using Python 3.6.X the imports of spatialmath.base can not be resolved properly. Changing the imports accordingly fixed the problem.
```
#import spatialmath.base as base
from spatialmath import base as base
```

Could this also be addressed in one of the next releases of the package?
